# Basic
title: 剑尖博客
subtitle: iOS开发者
# welcome_message: ObjC 中国
# description: 
# creator: <a href="http://onev.cat">@onevcat</a>

url: "http://zyuanming.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

blog_button:
    title: 博客
    description: 访问博客

nav:
    - {title: 简历, description: 我的简历, url: 'http://zyuanming.github.io/about/'}
    - {title: 关于, description: 了解更多关于我, url: 'http://zyuanming.github.io/about/'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: yuanming
    # duoshuo:
# Social
social:
    weibo: yuanming
    github: zyuanming
    twitter: yuanming
    mail: zyuanming@outlook.com

# Google Analytics
ga:
    id: UA-39496860-2
    host: zyuanming.github.io
